site_name: Rakuten Docs

nav:
  - Approach: index.md
  - PSO: pso.md
  - Quantization: Quantization.md
  - GPT:
    - Introduction to GPT: 00_GPTIntro.md
    - Training GPT: 01_GPTTraining.md
  - Finetuning: 
    - Finetuning Intro: finetuning.md
    - GPT2: Finetuning GPT2.md
  

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
 - material/group:
      plugins:
        - mkdocs-material
        - blog
        - group
        - offline
        - search
        - social
        - tags

# Add social media links here
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/iamrajharshit/ProjectRakuten
    name: GitHub
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/iamrajharshit
    name: LinkedIn
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/iamrajharshit
    name: Twitter


markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  



